identity:
  agent_name: "{agent_name}"
  admin_name: "AdminName"
  admin_tg_id: 123456789 # ID вашего Telegram-аккаунта


llm:
  model_name: "gemini-flash-latest"
  is_main_model_multimodal: true # Если у model_name поддерживается мультимодальность - ставьте true, В противном случае - false

  multimodal_model: "gemini-3.1-flash-lite-preview" # Подмодель, которая будет использоваться для понимания мультимодальности 
  # (в случае того, если is_main_model_multimodal: false)

  available_models:
    - "gemini-3.1-pro-preview"
    - "gemini-3.1-flash-lite-preview"
    - "gemini-3-flash-preview"
    - "gpt-5.4"
    - "claude-opus-4-6"
    # ...можете добавлять свои

  temperature: 0.7
  max_react_steps: 15 # Для главного мозга

  limits:
    max_file_read_chars: 80000 # Макс. количество символов при чтении файлов в Sandbox
    max_web_read_chars: 15000
    action_details_max_chars: 200
    image_max_size: [1500, 1500]

  # Настройка глубины контекста для разных циклов
  context_depth:
    # Цикл реакции на входящие события (входящие сообщения, отчеты и т.д.)
    event_driven:
      thoughts_limit: 5  # Сколько последних n мыслей агента скидывать в контекст
      actions_limit: 15  # Последние n действий агента
      dialogue_limit: 20 # Последние n записей диалога
      
    # Цикл проактивности
    proactivity:
      thoughts_limit: 8
      actions_limit: 20
      dialogue_limit: 25
      
    # Цикл интроспекции
    thoughts:
      thoughts_limit: 10
      actions_limit: 25
      dialogue_limit: 30


swarm:
  sybagent_model: "gemini-3.1-flash-lite-preview"
  max_sybagent_steps: 10
  report_max_chars: 8000


rhythms:
  proactivity_interval_sec: 900 # Интервал цикла проактивности
  min_proactivity_cooldown_sec: 120 

  thoughts_interval_sec: 1800

  reduction_medium_sec: 180 # При появлении события уровня MEDIUM следующий цикл проактивности вызывается на n секунд раньше
  reduction_low_sec: 60

  telemetry_poll_sec: 60 # Интервал сбора телеметрии
  weather_poll_sec: 1800 # Интервал сбора погоды


memory:
  mental_state:
    active_focus_ttl_hours: 12 # Сколько часов сущности уровня medium висят в активном фокусе (после - переходят в фоновую память)

  # Векторная база
  chroma_db_path: "workspace/_data/chroma_db/"
  similarity_threshold: 0.43 # Порог схожести записей при поиске в ChromaDB
  embedding_model: 
    name: "BAAI/bge-m3"
    local_path: "src/layer00_utils/local_models/models--BAAI--bge-m3" # Локальная модель эмбеддингов (установится автоматически)
  vector_rag:
    max_results: 5

  # Графовая база
  kuzu_db_path: "workspace/_data/kuzu_db" # Графовая база
  graph_rag:
    max_direct_edges: 20
    max_indirect_edges: 15

  workspace_garbage_collector:
    temp_files_ttl_hours: 48 # Автоудаление временных файлов


telegram:
  agent_session_name: "agent_session"
  ignored_users: [708513, 777000] # Reply и служебные чат Telegram


system:
  weather_city: "Moscow"
  logging_level: "INFO"
  log_retention_days: 14

  flags:
    enable_proactivity: true            
    enable_thoughts: true               
    dump_llm_context: true
    headless_mode: true  